# Generated by Django 4.2.3 on 2023-08-08 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realtors', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='realtors',
            old_name='decription',
            new_name='description',
        ),
    ]
