# Generated by Django 4.2.3 on 2023-07-27 09:58

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('realtors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sulg', models.CharField(max_length=225, unique=True)),
                ('title', models.CharField(max_length=225)),
                ('address', models.CharField(max_length=225)),
                ('city', models.CharField(max_length=225)),
                ('state', models.CharField(max_length=225)),
                ('zipcode', models.CharField(max_length=225)),
                ('decription', models.TextField(blank=True)),
                ('sale_type', models.CharField(choices=[('For Sale', 'For Sale'), ('For Rent', 'For Rent')], default='For Sale', max_length=225)),
                ('price', models.IntegerField()),
                ('bedrooms', models.IntegerField()),
                ('bathrooms', models.DecimalField(decimal_places=1, max_digits=2)),
                ('home_type', models.CharField(choices=[('House', 'House'), ('CONDO', 'CONDO'), ('Bunglo', 'Bunglo'), ('Plot', 'Plot'), ('Flat', 'Flat')], max_length=225)),
                ('sqrft', models.IntegerField()),
                ('house_open', models.BooleanField(default=False)),
                ('photo_main', models.ImageField(upload_to='photo/%Y/%m/%d')),
                ('photo1', models.ImageField(blank=True, upload_to='photo/%Y/%m/%d')),
                ('photo2', models.ImageField(blank=True, upload_to='photo/%Y/%m/%d')),
                ('photo3', models.ImageField(blank=True, upload_to='photo/%Y/%m/%d')),
                ('photo4', models.ImageField(blank=True, upload_to='photo/%Y/%m/%d')),
                ('photo5', models.ImageField(blank=True, upload_to='photo/%Y/%m/%d')),
                ('is_published', models.BooleanField(default=True)),
                ('list_date', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('realtor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='realtors.realtors')),
            ],
        ),
    ]
