# Generated by Django 4.2.3 on 2023-07-27 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='home_type',
            field=models.CharField(choices=[('House', 'House'), ('CONDO', 'Condo'), ('Bunglo', 'Bunglo'), ('Plot', 'Plot'), ('Flat', 'Flat')], default='House', max_length=225),
        ),
    ]
