# Generated by Django 4.2.3 on 2023-07-27 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0002_alter_listing_home_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='sulg',
            new_name='slug',
        ),
    ]
