# Generated by Django 4.2.3 on 2023-08-03 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0005_rename_description_listing_decription_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='house_open',
            new_name='open_house',
        ),
    ]
