# Generated by Django 4.2.3 on 2023-08-04 03:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0007_rename_photo1_listing_photo_1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='decription',
            new_name='description',
        ),
    ]
